#!/usr/bin/python
#
#  vacdepo-cgi - HTTPS depository service 
#
#  Andrew McNab, University of Manchester.
#  Copyright (c) 2013-9. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or
#  without modification, are permitted provided that the following
#  conditions are met:
#
#    o Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer. 
#    o Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution. 
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#              This software is part of the Vac project: 
#                   https://www.gridpp.ac.uk/vac/
#

import os
import re
import sys
import time
import tempfile

if '/../' in os.environ['REQUEST_URI']:
  # Don't even go there...
  print 'Status: 404 Not Found'
  print
  print 'Not Found'
  sys.exit(0)

try:
  firstDir  = os.environ['REQUEST_URI'].split('/')[1]
  filePath  = os.environ['REQUEST_URI'].replace('//','/').split('?')[0]
except:
  print 'Status: 404 Not Found'
  print
  print 'Not Found'
  sys.exit(0)

try:
  # There must be a vacdepo-readers list of X.509 DNs for read control
  # to be enabled
  readList = open('/etc/vacdepo-readers/' + firstDir, 'r').read().splitlines()
except:
  pass
else:
  foundDN = False

  if 'SSL_CLIENT_S_DN' in os.environ and os.environ['SSL_CLIENT_S_DN']:
    # Look for DN or DN+'/CN=...' (ie proxy) in access list
    for readListDN in readList:
      if os.environ['SSL_CLIENT_S_DN'] == readListDN or os.environ['SSL_CLIENT_S_DN'].startswith(readListDN + '/CN='):
        foundDN = True
        break
      
  if not foundDN:
    # Unless we found a matching DN then refuse
    print 'Status: 403 Forbidden'
    print
    print 'Forbidden - read access not allowed'
    sys.exit(0)

if os.environ['REQUEST_URI'] == '/':
  # No browsing of the first level directory names
  print 'Status: 403 Directory listing forbidden'
  print
  print 'Directory listing forbidden'
  sys.exit(0)

if os.environ['REQUEST_METHOD'] == 'GET' or os.environ['REQUEST_METHOD'] == 'HEAD':

  absoluteFilePath = os.environ['DOCUMENT_ROOT'] + '/' + filePath
  
  if os.path.isfile(absoluteFilePath):
    print 'Status: 200 OK'
    stat = os.stat(absoluteFilePath)
    print 'Content-Length: ' + str(stat.st_size)
    print 'Content-Type: text/plain'
    print 'Last-Modified: ' + time.strftime("%a, %d %b %Y %T GMT", time.gmtime(stat.st_mtime))
    print
  
    if os.environ['REQUEST_METHOD'] == 'GET':
      try:
        print open(absoluteFilePath, 'r').read()
      except:
        pass

  elif os.path.isdir(absoluteFilePath) and not os.environ['REQUEST_URI'].endswith('/'):
    print 'Status: 301 Moved Permanently'
    print 'Location: https://' + \
                     os.environ['SERVER_NAME'] + \
                     ('' if os.environ['SERVER_PORT'] == '443' else (':' + os.environ['SERVER_PORT'])) + \
                     os.environ['REQUEST_URI'] + '/'
    print

  elif os.path.isdir(absoluteFilePath):
    print 'Status: 200 OK'
    print 'Content-Type: text/html'
    print
    print '<html><head><title>Directory ' + os.environ['REQUEST_URI'] + '</title></head>'
    print '<body><h1>Directory ' + os.environ['REQUEST_URI'] + '</h1>'

    try:
      os.chdir(absoluteFilePath)
      dirList = sorted(os.listdir('.'), key=os.path.getmtime, reverse=True)
    except:
      pass
    else:    
      print '<pre>'
      
      for fileName in dirList:
        print time.asctime(time.gmtime(os.path.getmtime(fileName))) \
              + ' <a href="' + fileName + '">' + fileName + '</a>'
      
      print '</pre>'

    print '</body></html>'

  else:
    print 'Status: 404 Not Found'
    print
    print 'Not Found'

  sys.exit(0)

# Writing methods have extra restrictions

if 'SSL_CLIENT_S_DN' not in os.environ or not os.environ['SSL_CLIENT_S_DN']:
  print 'Status: 403 Forbidden - no client X.509 authentication'
  print
  print 'Forbidden - no client X.509 authentication'
  sys.exit(0)

try:
  # There must be a vacdepo-writers list of X.509 DNs for this first level
  # directory for writing to be allowed in it
  writeList = open('/etc/vacdepo-writers/' + firstDir, 'r').read().splitlines()
except:
  print 'Status: 403 Forbidden - write access not enabled'
  print
  print 'Forbidden - write access not enabled'
  sys.exit(0)

# Look for DN or DN+'/CN=...' (ie proxy) in access list
foundDN = False
for writeListDN in writeList:
  if os.environ['SSL_CLIENT_S_DN'] == writeListDN or os.environ['SSL_CLIENT_S_DN'].startswith(writeListDN + '/CN='):
    foundDN = True
    break

if not foundDN:
  # X.509 DN must be on the vacdepo-writers list for this first level directory
  # for writing here to be allowed
  print 'Status: 403 Forbidden - write access not allowed'
  print
  print 'Forbidden - write access not allowed'
  sys.exit(0)

if os.environ['REQUEST_METHOD'] == 'PUT':
  absoluteFilePath = os.environ['DOCUMENT_ROOT'] + filePath

  try:
    os.makedirs('/'.join(absoluteFilePath.split('/')[:-1]))
  except:
    pass

  tempFileName = None

  try:
    # Try atomic update of absoluteFilePath using a temporary file and a rename
    fd, tempFileName = tempfile.mkstemp(prefix = '/'.join(absoluteFilePath.split('/')[:-1]) + '/.vacdepo.')
    os.write(fd, sys.stdin.read())
    os.close(fd)
    os.rename(tempFileName, absoluteFilePath)

  except:
    try:
      os.remove(tempFileName)
    except:
      pass

    print 'Status: 500 Internal Server Error writing file'
    print
    print 'Internal Server Error writing file'

  else:
    # All parent directories get time stamp updated too
    recursePath = os.environ['DOCUMENT_ROOT']
    for dir in filePath.split('/')[1:-1]:
      recursePath += '/' + dir
      os.utime(recursePath, None)

    print 'Status: 200 OK'  
    print
      
  sys.exit(0)
  
print 'Status: 405 Method not allowed'
print
print 'Method not allowed'
sys.exit(0)
